name: Docs Only CI

on:
  push:
    paths:
      - 'README.md
      - 'docs/**'

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print message
        run: echo "docs/ ディレクトリ内が変更されたため、doc-check を実行します"
